//! Bakes `teammates/` into the binary.
//!
//! `horch install` is a plain binary copy, so a fleet must be spawnable without
//! the repo checked out. The compiled-in copies are the fallback layer of the
//! roster; a runtime directory overlays them when one is present.
//!
//! The list is globbed rather than hand-written so that "adding a file to the
//! folder adds a teammate" holds for the compiled binary too, and a file can
//! never be added on disk yet forgotten in Rust.

use std::fmt::Write as _;
use std::path::Path;

fn main() {
    let crate_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let root = crate_dir.parent().unwrap().parent().unwrap();
    let teammates = root.join("teammates");

    println!("cargo:rerun-if-changed={}", teammates.display());
    println!("cargo:rerun-if-changed={}", teammates.join("_base").display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut out = String::new();
    out.push_str("// @generated by build.rs from teammates/. Do not edit.\n");

    emit(&mut out, "BUILTIN_TEAMMATES", &teammates, |name| {
        !name.starts_with('_')
    });
    emit(&mut out, "BUILTIN_BASES", &teammates.join("_base"), |_| true);

    let template = teammates.join("_template.md");
    println!("cargo:rerun-if-changed={}", template.display());
    writeln!(
        out,
        "pub static TEMPLATE: &str = include_str!(r\"{}\");",
        template.display()
    )
    .unwrap();

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("builtin_teammates.rs");
    std::fs::write(dest, out).unwrap();
}

/// Emit one `&[(name, contents)]` table for every `*.md` in `dir` passing `keep`.
fn emit(out: &mut String, ident: &str, dir: &Path, keep: fn(&str) -> bool) {
    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(read) = std::fs::read_dir(dir) {
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("md") {
                continue;
            }
            let stem = path.file_stem().unwrap().to_string_lossy().to_string();
            if stem == "README" || !keep(&stem) {
                continue;
            }
            println!("cargo:rerun-if-changed={}", path.display());
            entries.push((stem, path.display().to_string()));
        }
    }
    // Sorted so the generated file is stable across filesystems.
    entries.sort();

    writeln!(out, "pub static {ident}: &[(&str, &str)] = &[").unwrap();
    for (stem, path) in entries {
        writeln!(out, "    (\"{stem}\", include_str!(r\"{path}\")),").unwrap();
    }
    out.push_str("];\n");
}
